name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  core-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Enable Corepack
        run: corepack enable

      - name: Install deps
        run: pnpm install

      - name: Run dialog-core tests
        run: pnpm -C packages/dialog-core test --run








